### ISSUE TITLE
Option to create additional files & use of sw_include function

### ISSUE THREAD

**Issue by MarcelDanes** [dneustadt/DneTemplateManager#6]
I would like to add new files. Like MyCustomDesign.html.twig
It would be great to have button to cerate a new empty file.

To use this new files it is necessary to use the function sw_include.
Example:
{% sw_include '@.customTemplate/storefront/mystuff/MyCustomDesign.html.twig' %}

Curretnly it dosen´t work.Maybe it caused by the dot in the folder name.

**Comment by dneustadt** [comment]
Hi, due to time constraints I can't really promise anything but creation of new template files through the extension would possibly be among upcoming features.
For the time being you could try to include manually created templates by using:
```
{% sw_include '@DneTemplateManager/storefront/mystuff/MyCustomDesign.html.twig' %}
```
The folder `.customTemplate` is still part of the extension and was only put outside of the directory scope of the extension as to avoid having updates of the extension delete it's contents. Theoretically inclusion by referencing the extension's name should still work though.
